data-path="Node-00/data"
genesis-file="genesis.json"
p2p-port="30303"

rpc-http-enabled=true
rpc-http-port="8545"
rpc-http-api=['ETH','NET','CLIQUE','PERM','EEA','PRIV']
rpc-http-cors-origins=["all"]

host-whitelist=["*"]

permissions-nodes-config-file-enabled=true
permissions-accounts-config-file-enabled=true

privacy-enabled=true
privacy-url="http://127.0.0.1:8888"
privacy-public-key-file="Node-00/Orion/Node00Key.pub"

min-gas-price=0

