# FULL DOC https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/ --------------------- #

# ----------------------------------------------------------------------------------------------- #
# NETWORK SETTINGS ------------------------------------------------------------------------------ #
data-path="data"                    # The path to the Besu data directory. 
genesis-file="../../genesis.json"   # Genesis file is used to create a custom network.
network-id="2020"
# network="rinkeby"                 # Uncomment to use Rinkeby which is a PoA test network w Clique (must comment genesis-file obv).
# node-private-key-file="path"      # Unnecessary. Defaults to the key file in the data directory.
min-gas-price=0                     # The minimum price that a transaction offers for it to be included in a mined block.

# P2P SETTINGS + BOOTNODES ---------------------------------------------------------------------- #
# ----------------------------------------------------------------------------------------------- #
p2p-enabled=true
p2p-host="127.0.0.1"
p2p-port="30304"
max-peers=20                        # Specifies the maximum P2P connections that can be established.
discovery-enabled=true              # Enables or disables P2P peer discovery. 
bootnodes=[
    "enode://6d3ecbcded1ccb97c4e9b569929a7df92fe3dec4b8296f93f5db1b82c4e9088913d903ac5c134587fd47adfa32803eac108c242d63f2a97490e6a59cfeb93a76@127.0.0.1:30303",
#   "enode://cdad2d7b6e7ac2c80b973dce287c178956ad140373c246d3caceeb855ee2e4378b9017b77fcba6ec6031806fa06731120f072747ab15c13b873bac1a1edad3f1@127.0.0.1:30304",
    "enode://811d59c076493511d340415ef3bcffd233dc08ead9e82123845c29fa68f61c82e499469ac8ade177532888c713878be151e17efb3f8e127ba81cd49ee9b05cff@127.0.0.1:30305",
    "enode://0b2d91d1dffeec969406b3ddfab7b9f3e1ce5805fb99580723e0cb9347bf49a706d5953d2626cbd58ca5ca27808247c3c3daab461867addf450a9249ae3e79a5@127.0.0.1:30306"
]

# RPC SETTINGS + APIs --------------------------------------------------------------------------- #
# ----------------------------------------------------------------------------------------------- #
rpc-http-enabled=true
rpc-http-port="8546"
rpc-http-api=['ETH','NET','CLIQUE','PERM','EEA','PRIV']
rpc-http-cors-origins=["all"]
rpc-ws-enabled=true
rpc-ws-port=9546
host-whitelist=["*"]                # Comma-separated list of hostnames to allow access to the JSON-RPC API.

# PERMISSION + PRIVACY SETTINGS ----------------------------------------------------------------- #
# ----------------------------------------------------------------------------------------------- #
#permissions-accounts-config-file="path"        # Unnecessary. Defaults to permissions_config.toml in the data directory.
permissions-nodes-config-file-enabled=false
permissions-accounts-config-file-enabled=false
privacy-enabled=true
privacy-url="http://127.0.0.1:8891"
privacy-public-key-file="Orion/key.pub"


# ADDITIONAL SETTINGS --------------------------------------------------------------------------- #
# ----------------------------------------------------------------------------------------------- #
identity="GUCCI-00"             # Name for the node for some Ethereum network explorers.
logging="INFO"                  # Log levels are OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# metrics-enabled=true          # Set to true to enable the metrics exporter (Prometheus in polling) -> not using it anymore, ethstats is enough
# metrics-port="9546"