# Valid TOML config file
data-path="Node-00/data" # Path

# Network
#bootnodes=["enode://6d3ecbcded1ccb97c4e9b569929a7df92fe3dec4b8296f93f5db1b82c4e9088913d903ac5c134587fd47adfa32803eac108c242d63f2a97490e6a59cfeb93a76@127.0.0.1:30303"]
host-whitelist=["*"]

p2p-port=30000
max-peers=42

rpc-ws-port=9101

rpc-http-enabled=true
rpc-http-port=8535
rpc-http-cors-origins = ["all"]
rpc-http-api = ['ADMIN','ETH','NET','WEB3','CLIQUE','PERM','DEBUG']

# Chain
genesis-file="/home/aless/Documents/dev/unimib/demos/D01-permissioned-network/genesis.json" # Path to the custom genesis file
min-gas-price=0

# Privacy
#privacy-enabled=false
#privacy-public-key-file="home / <user> /besu-test/node_1/orion/node1Key.pub "
#privacy-url = "http://localhost:8880"



